# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Too many projects, too little time'
tagline:             ''
description:         ''
url:                 http://jdutta.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Joy Dutta
  url:               ''
  email:             therider AT gmail

# Custom vars
version:             1.0.0
